# Generated by Django 4.0 on 2021-12-31 21:03

from django.db import migrations, models
import django.db.models.deletion
import empresas.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='briefing',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Briefing'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=empresas.models.diretorio_empresa, verbose_name='Arquivo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
